from .ttm import TTM
from .wttm import WTTM
from .kd import DistillKL
from .crd import CRDLoss
from .itrd import ITLoss
from .dist import DIST
from .abkl import ABKL
from .dkd import DKD
from .ls import LS
from .mlkd import MLKD